ibmcloud_api_key = "EWFCRUDOAyuSlXfmYkjYfkU7ycTMe2Wnv6o4vjHD7DT8"
iaas_classic_username = "YOUR_IBM_CLOUD_USERNAME"
iaas_classic_api_key = "YOUR_CLASSIC_INFRASTRUCTURE_API_KEY"
region = "us-south"
my_ssh_key_name = "vpcvsisamplekey"
